name: API Health Check Scheduler

on:
  schedule:
    - cron: '0,12,24,36,48 * * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Health Check API
        run: |
          curl -X GET "${{ secrets.HEALTHCHECK_API }}" \
               -H "Accept: application/json" \
               -H "User-Agent: GitHub-Actions-Health-Check" \
               -w "HTTP Status: %{http_code}\nResponse Time: %{time_total}s\n" \
               -s -S